In [88]:
import numpy as np
import pandas as pd

In [89]:
df = pd.read_csv("medicine_dataset.csv")

/var/folders/4l/8ylvn2497l36_nw4mhtqdy840000gn/T/ipykernel_1940/2728295947.py:1: DtypeWarning: Columns (42,43,44,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("medicine_dataset.csv")

In [90]:
df

,id,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,...,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class
0,1,augmentin 625 duo tablet,Penciclav 500 mg/125 mg Tablet,Moxikind-CV 625 Tablet,Moxiforce-CV 625 Tablet,Fightox 625 Tablet,Novamox CV 625mg Tablet,Vomiting,Nausea,Diarrhea,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,NaN,No,ANTI INFECTIVES,NaN
1,2,azithral 500 tablet,Zithrocare 500mg Tablet,Azax 500 Tablet,Zady 500 Tablet,Cazithro 500mg Tablet,Trulimax 500mg Tablet,Vomiting,Nausea,Abdominal pain,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides
2,3,ascoril ls syrup,Solvin LS Syrup,Ambrodil-LX Syrup,Zerotuss XP Syrup,Capex LS Syrup,Broxum LS Syrup,Nausea,Vomiting,Diarrhea,...,NaN,Treatment of Cough with mucus,NaN,NaN,NaN,NaN,NaN,No,RESPIRATORY,NaN
3,4,allegra 120mg tablet,Lcfex Tablet,Etofex 120mg Tablet,Nexofex 120mg Tablet,Fexise 120mg Tablet,Histafree 120 Tablet,Headache,Drowsiness,Dizziness,...,NaN,Treatment of Sneezing and runny nose due to al...,Treatment of Allergic conditions,NaN,NaN,NaN,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation)
4,5,avil 25 tablet,Eralet 25mg Tablet,NaN,NaN,NaN,NaN,Sleepiness,Dryness in mouth,NaN,...,NaN,Treatment of Allergic conditions,NaN,NaN,NaN,NaN,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248213,248214,zestrain 100mg/325mg/250mg tablet mr,Aclotec MR 100mg/325mg/250mg Tablet,SAMONEC MR TABLET,Uniclof 100mg/325mg/250mg Tablet MR,Macito 100mg/325mg/250mg Tablet MR,Rumatin 100mg/325mg/250mg Tablet MR,Nausea,Vomiting,Heartburn,...,NaN,Treatment of Muscular pain,NaN,NaN,NaN,NaN,NaN,No,PAIN ANALGESICS,NaN
248214,248215,zoxinace 200mg tablet sr,Algic 200mg Tablet SR,Topnac 200mg Tablet SR,Kindac 200mg Tablet SR,Ultranac 200mg Tablet SR,Bignac 200mg Tablet SR,Dizziness,Indigestion,Nausea,...,NaN,Pain relief,NaN,NaN,NaN,NaN,Dichlorobenzenes Derivative,No,PAIN ANALGESICS,NSAID's- Non-Selective COX 1&2 Inhibitors (ace...
248215,248216,zivex 25mg tablet,HD Zine 25mg Tablet,Hydrocas 25mg Tablet,Hyzox 25 Tablet,Hydil 25mg Tablet,Zyzine 25mg Tablet,Sedation,Nausea,Vomiting,...,NaN,Treatment of Anxiety,Treatment of Skin conditions with inflammation...,NaN,NaN,NaN,Piperazine Derivative,No,RESPIRATORY,H1 Antihistaminics (First Generation)
248216,248217,zi fast 500mg injection,Zycin 500mg Injection,Aziwok 500mg Injection,Azirow 500mg Injection,Toracin 500mg Injection,Azymed 500mg Injection,"Injection site reactions (pain, swelling, redn...",Vomiting,Nausea,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides
248217,248218,zyvocol 1% dusting powder,Canazole Dusting Powder,Clotrex Dusting Powder,AF -C Dusting Powder,Klo-Aid Dusting Powder,Nuforce Dusting Powder,Blisters,Skin peeling,Swelling,...,NaN,Treatment of Fungal skin infections,NaN,NaN,NaN,NaN,Azole derivatives {Imidazoles},No,DERMA,Fungal ergosterol synthesis inhibitor

In [91]:
df.head()

,id,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,...,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class
0,1,augmentin 625 duo tablet,Penciclav 500 mg/125 mg Tablet,Moxikind-CV 625 Tablet,Moxiforce-CV 625 Tablet,Fightox 625 Tablet,Novamox CV 625mg Tablet,Vomiting,Nausea,Diarrhea,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,NaN,No,ANTI INFECTIVES,NaN
1,2,azithral 500 tablet,Zithrocare 500mg Tablet,Azax 500 Tablet,Zady 500 Tablet,Cazithro 500mg Tablet,Trulimax 500mg Tablet,Vomiting,Nausea,Abdominal pain,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides
2,3,ascoril ls syrup,Solvin LS Syrup,Ambrodil-LX Syrup,Zerotuss XP Syrup,Capex LS Syrup,Broxum LS Syrup,Nausea,Vomiting,Diarrhea,...,NaN,Treatment of Cough with mucus,NaN,NaN,NaN,NaN,NaN,No,RESPIRATORY,NaN
3,4,allegra 120mg tablet,Lcfex Tablet,Etofex 120mg Tablet,Nexofex 120mg Tablet,Fexise 120mg Tablet,Histafree 120 Tablet,Headache,Drowsiness,Dizziness,...,NaN,Treatment of Sneezing and runny nose due to al...,Treatment of Allergic conditions,NaN,NaN,NaN,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation)
4,5,avil 25 tablet,Eralet 25mg Tablet,NaN,NaN,NaN,NaN,Sleepiness,Dryness in mouth,NaN,...,NaN,Treatment of Allergic conditions,NaN,NaN,NaN,NaN,Pyridines Derivatives,No,RESPIRATORY,H1 Antihistaminics (First Generation)

In [92]:
df.shape

(248218, 58)

In [93]:
df.tail()

,id,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,...,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class
248213,248214,zestrain 100mg/325mg/250mg tablet mr,Aclotec MR 100mg/325mg/250mg Tablet,SAMONEC MR TABLET,Uniclof 100mg/325mg/250mg Tablet MR,Macito 100mg/325mg/250mg Tablet MR,Rumatin 100mg/325mg/250mg Tablet MR,Nausea,Vomiting,Heartburn,...,NaN,Treatment of Muscular pain,NaN,NaN,NaN,NaN,NaN,No,PAIN ANALGESICS,NaN
248214,248215,zoxinace 200mg tablet sr,Algic 200mg Tablet SR,Topnac 200mg Tablet SR,Kindac 200mg Tablet SR,Ultranac 200mg Tablet SR,Bignac 200mg Tablet SR,Dizziness,Indigestion,Nausea,...,NaN,Pain relief,NaN,NaN,NaN,NaN,Dichlorobenzenes Derivative,No,PAIN ANALGESICS,NSAID's- Non-Selective COX 1&2 Inhibitors (ace...
248215,248216,zivex 25mg tablet,HD Zine 25mg Tablet,Hydrocas 25mg Tablet,Hyzox 25 Tablet,Hydil 25mg Tablet,Zyzine 25mg Tablet,Sedation,Nausea,Vomiting,...,NaN,Treatment of Anxiety,Treatment of Skin conditions with inflammation...,NaN,NaN,NaN,Piperazine Derivative,No,RESPIRATORY,H1 Antihistaminics (First Generation)
248216,248217,zi fast 500mg injection,Zycin 500mg Injection,Aziwok 500mg Injection,Azirow 500mg Injection,Toracin 500mg Injection,Azymed 500mg Injection,"Injection site reactions (pain, swelling, redn...",Vomiting,Nausea,...,NaN,Treatment of Bacterial infections,NaN,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides
248217,248218,zyvocol 1% dusting powder,Canazole Dusting Powder,Clotrex Dusting Powder,AF -C Dusting Powder,Klo-Aid Dusting Powder,Nuforce Dusting Powder,Blisters,Skin peeling,Swelling,...,NaN,Treatment of Fungal skin infections,NaN,NaN,NaN,NaN,Azole derivatives {Imidazoles},No,DERMA,Fungal ergosterol synthesis inhibitor

In [94]:
df.isnull().sum()

id                        0
name                      0
substitute0            9597
substitute1           14351
substitute2           17985
substitute3           21362
substitute4           24256
sideEffect0               0
sideEffect1            9802
sideEffect2           18718
sideEffect3           40580
sideEffect4           84658
sideEffect5          116960
sideEffect6          156361
sideEffect7          180468
sideEffect8          199712
sideEffect9          210510
sideEffect10         220944
sideEffect11         227887
sideEffect12         231936
sideEffect13         233491
sideEffect14         237799
sideEffect15         240537
sideEffect16         242209
sideEffect17         242836
sideEffect18         243703
sideEffect19         244272
sideEffect20         244995
sideEffect21         245093
sideEffect22         245170
sideEffect23         245313
sideEffect24         245495
sideEffect25         246715
sideEffect26         246715
sideEffect27         246724
sideEffect28         246724
sideEffect29         246780
sideEffect30         246889
sideEffect31         246889
sideEffect32         246890
sideEffect33         247049
sideEffect34         247052
sideEffect35         248216
sideEffect36         248216
sideEffect37         248216
sideEffect38         248216
sideEffect39         248216
sideEffect40         248216
sideEffect41         248216
use0                      0
use1                 174853
use2                 219911
use3                 240839
use4                 243247
Chemical Class       110427
Habit Forming             0
Therapeutic Class        69
Action Class         110182
dtype: int64

In [95]:
df.describe()

                  id
count  248218.000000
mean   124109.500000
std     71654.508896
min         1.000000
25%     62055.250000
50%    124109.500000
75%    186163.750000
max    248218.000000

In [96]:
df = df.fillna(" none ")

In [97]:
df.sample()

,id,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,...,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class
236970,236971,wozzok 200 capsule,Candirap 200 Capsule,Afitra 200 Capsule,Canditral 200 Capsule,Syntran 200 Capsule,Tinitraz 200 Capsule,Nausea,Common cold,Cough,...,none,Treatment of Fungal infections,none,none,none,none,Azoles {Triazoles},No,OPHTHAL,Fungal ergosterol synthesis inhibitor

In [98]:
df.duplicated().sum()

np.int64(0)

In [99]:
df.isnull().sum()

id                   0
name                 0
substitute0          0
substitute1          0
substitute2          0
substitute3          0
substitute4          0
sideEffect0          0
sideEffect1          0
sideEffect2          0
sideEffect3          0
sideEffect4          0
sideEffect5          0
sideEffect6          0
sideEffect7          0
sideEffect8          0
sideEffect9          0
sideEffect10         0
sideEffect11         0
sideEffect12         0
sideEffect13         0
sideEffect14         0
sideEffect15         0
sideEffect16         0
sideEffect17         0
sideEffect18         0
sideEffect19         0
sideEffect20         0
sideEffect21         0
sideEffect22         0
sideEffect23         0
sideEffect24         0
sideEffect25         0
sideEffect26         0
sideEffect27         0
sideEffect28         0
sideEffect29         0
sideEffect30         0
sideEffect31         0
sideEffect32         0
sideEffect33         0
sideEffect34         0
sideEffect35         0
sideEffect36         0
sideEffect37         0
sideEffect38         0
sideEffect39         0
sideEffect40         0
sideEffect41         0
use0                 0
use1                 0
use2                 0
use3                 0
use4                 0
Chemical Class       0
Habit Forming        0
Therapeutic Class    0
Action Class         0
dtype: int64

In [100]:
df['Action Class']

0                                                     none
1                                                Macrolides
2                                                     none
3                    H1 Antihistaminics (second Generation)
4                     H1 Antihistaminics (First Generation)
                                ...
248213                                                none
248214    NSAID's- Non-Selective COX 1&2 Inhibitors (ace...
248215                H1 Antihistaminics (First Generation)
248216                                           Macrolides
248217                Fungal ergosterol synthesis inhibitor
Name: Action Class, Length: 248218, dtype: object

In [101]:
df['Habit Forming'] = (df['Habit Forming'] == 'yes').astype(int)

In [102]:
(df['Habit Forming'] == 1).sum()

np.int64(0)

In [103]:
# None are addictive drugs , drop col.

In [104]:
df = df.drop(columns=['Habit Forming'])

In [105]:
df = df.drop(columns=['id'])

In [106]:
df.sample()

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,...,sideEffect40,sideEffect41,use0,use1,use2,use3,use4,Chemical Class,Therapeutic Class,Action Class
171529,navikof g syrup,Silkof X Syrup,Cobury-AX Syrup,Olin Syrup,Corphen A Syrup,Myflox GT Syrup Sugar Free,Nausea,Diarrhea,Vomiting,Dizziness,...,none,none,Cough,none,none,none,none,none,RESPIRATORY,none

In [107]:
# PS 
#Given a drug (or symptoms), build a system that:
#Classifies drug category
#Predicts risk (side effects / addictive flag)
#Recommends safer alternatives
#Explains reasoning (NLP-based)

In [108]:
use_cols = [col for col in df.columns if col.startswith('use')]
side_cols = [col for col in df.columns if col.startswith('sideEffect')]

df['uses'] = df[use_cols].apply(
    lambda row: ' '.join([
        str(x).strip() for x in row 
        if pd.notna(x) and str(x).strip().lower() != 'none' and str(x).strip() != ''
    ]),
    axis=1
)

df['side_effects'] = df[side_cols].apply(
    lambda row: ' '.join([
        str(x).strip() for x in row 
        if pd.notna(x) and str(x).strip().lower() != 'none' and str(x).strip() != ''
    ]),
    axis=1
)

def build_description(row):
    parts = []
    
    if row['uses']:
        parts.append("Uses: " + row['uses'])
        
    if row['side_effects']:
        parts.append("Side effects: " + row['side_effects'])
        
    return ". ".join(parts)

df['Description'] = df.apply(build_description, axis=1)

In [109]:
df.sample(2)

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,...,use1,use2,use3,use4,Chemical Class,Therapeutic Class,Action Class,uses,side_effects,Description
145566,misoprost 100mg tablet,none,none,none,none,none,Cramps,Nausea,Vomiting,Diarrhea,...,Treatment of Post-delivery bleeding,none,none,none,Prostaglandin Aanalogue,GASTRO INTESTINAL,Prostaglandin E1 (PGE1) analogue-obstetrics,Medical abortion Treatment of Post-delivery bl...,Cramps Nausea Vomiting Diarrhea Stomach cramp ...,Uses: Medical abortion Treatment of Post-deliv...
224297,urcef 200mg tablet,Cefilab 200 Tablet,Cefix 200 Tablet,Mahacef 200 Tablet,Cefi 200 Tablet,Ceftas 200 Tablet,Nausea,Stomach pain,Indigestion,Diarrhea,...,none,none,none,none,Broad spectrum (Third & fourth generation ceph...,ANTI INFECTIVES,Cephalosporins: 3 generation,Treatment of Bacterial infections,Nausea Stomach pain Indigestion Diarrhea,Uses: Treatment of Bacterial infections. Side ...

In [110]:
df['Description']

0         Uses: Treatment of Bacterial infections. Side ...
1         Uses: Treatment of Bacterial infections. Side ...
2         Uses: Treatment of Cough with mucus. Side effe...
3         Uses: Treatment of Sneezing and runny nose due...
4         Uses: Treatment of Allergic conditions. Side e...
                                ...
248213    Uses: Treatment of Muscular pain. Side effects...
248214    Uses: Pain relief. Side effects: Dizziness Ind...
248215    Uses: Treatment of Anxiety Treatment of Skin c...
248216    Uses: Treatment of Bacterial infections. Side ...
248217    Uses: Treatment of Fungal skin infections. Sid...
Name: Description, Length: 248218, dtype: object

In [111]:
sub_cols = [col for col in df.columns if col.startswith('substitute')]

df['substrates'] = df[sub_cols].apply(
    lambda row: ' '.join([
        str(x).strip() for x in row 
        if pd.notna(x) and str(x).strip().lower() != 'none' and str(x).strip() != ''
    ]),
    axis=1
)

In [112]:
df.sample(2)

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,...,use2,use3,use4,Chemical Class,Therapeutic Class,Action Class,uses,side_effects,Description,substrates
41817,cerin plus tablet,Dincerin Plus Tablet,Glucozone Tablet,Ostovit DM Tablet,G-Cerin Tablet,Kneejoint Care Tablet,Nausea,Diarrhea,Constipation,Indigestion,...,none,none,none,none,PAIN ANALGESICS,none,Osteoarthritis,Nausea Diarrhea Constipation Indigestion Heart...,Uses: Osteoarthritis. Side effects: Nausea Dia...,Dincerin Plus Tablet Glucozone Tablet Ostovit...
51948,celpod 200mg tablet,Gudcef 200 Tablet,Zipod 200mg Tablet,Brotacef 200mg Tablet,Oxipod 200mg Tablet,Monocef-O 200 Tablet,Rash,Nausea,Diarrhea,none,...,none,none,none,Broad Spectrum (Third & fourth generation ceph...,ANTI INFECTIVES,Cephalosporins: 3 generation,Treatment of Bacterial infections,Rash Nausea Diarrhea,Uses: Treatment of Bacterial infections. Side ...,Gudcef 200 Tablet Zipod 200mg Tablet Brotacef ...

In [115]:
df[['uses'] + use_cols].sample()

,uses,use0,use1,use2,use3,use4
92344,Treatment of Nausea Vomiting,Treatment of Nausea,Vomiting,none,none,none

In [116]:
df.sample()

,name,substitute0,substitute1,substitute2,substitute3,substitute4,sideEffect0,sideEffect1,sideEffect2,sideEffect3,...,use2,use3,use4,Chemical Class,Therapeutic Class,Action Class,uses,side_effects,Description,substrates
79980,dayaprox 500mg tablet er,Divalgress ER 500 Tablet,Divawave OD 500 Tablet ER,Ardiva 500mg Tablet ER,Valdiv ER 500 Tablet,Divalrate 500mg Tablet ER,Headache,Dizziness,Blurred vision,Weakness,...,Prevention of Migraine,none,none,Aliphatic Carboxylic acid Derivatives,NEURO CNS,Sodium channel modulators (AED),Treatment of Epilepsy/Seizures Treatment of Bi...,Headache Dizziness Blurred vision Weakness Abd...,Uses: Treatment of Epilepsy/Seizures Treatment...,Divalgress ER 500 Tablet Divawave OD 500 Table...

In [119]:
useful_cols = [
    'name',
    'substrates',
    'side_effects',
    'uses',        
    'Description',
    'Action Class',
    'Chemical Class',
    'Therapeutic Class'
]

In [121]:
df_clean = df[useful_cols].copy()
df_clean = df_clean[df_clean['Description'].str.strip() != '']
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
df_clean.to_csv('drug.csv', index=False)